version = 1

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  bootstrap_files = ["5000"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["5000"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/KOSASIH/Lineax"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs",
    "meteor"
  ]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "16"

[[analyzers]]
name = "ruby"
enabled = true

[[transformers]]
name = "standardrb"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true